// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_inicio_layout from "./routes/(inicio)/_layout.tsx";
import * as $_inicio_middleware from "./routes/(inicio)/_middleware.ts";
import * as $_inicio_carrito from "./routes/(inicio)/carrito.tsx";
import * as $_inicio_characters from "./routes/(inicio)/characters.tsx";
import * as $_inicio_favorites from "./routes/(inicio)/favorites.tsx";
import * as $_inicio_home from "./routes/(inicio)/home.tsx";
import * as $_inicio_spells from "./routes/(inicio)/spells.tsx";
import * as $_inicio_tienda from "./routes/(inicio)/tienda.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $BuyButton from "./islands/BuyButton.tsx";
import * as $Entry from "./islands/Entry.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $Star from "./islands/Star.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(inicio)/_layout.tsx": $_inicio_layout,
    "./routes/(inicio)/_middleware.ts": $_inicio_middleware,
    "./routes/(inicio)/carrito.tsx": $_inicio_carrito,
    "./routes/(inicio)/characters.tsx": $_inicio_characters,
    "./routes/(inicio)/favorites.tsx": $_inicio_favorites,
    "./routes/(inicio)/home.tsx": $_inicio_home,
    "./routes/(inicio)/spells.tsx": $_inicio_spells,
    "./routes/(inicio)/tienda.tsx": $_inicio_tienda,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/BuyButton.tsx": $BuyButton,
    "./islands/Entry.tsx": $Entry,
    "./islands/Header.tsx": $Header,
    "./islands/Star.tsx": $Star,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
